### ISSUE TITLE
'STORYBOOK_DSM' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by CharlJKruger** [InVisionApp/dsm-storybook-example-library#11]
After following the tutorial, https://support.invisionapp.com/hc/en-us/articles/360028510211-Configuring-the-Storybook-DSM-Integration#generating-an-authentication-token

Trying to publish or preview results in:

'STORYBOOK_DSM' is not recognized as an internal or external command

Using angular 7.2.0
storybook 5.1.9

addons.js

```
import '@storybook/addon-actions/register';
import '@storybook/addon-links/register';
import '@storybook/addon-notes/register';

import { registerDsm } from '@invisionapp/dsm-storybook/register';

registerDsm(process.env.STORYBOOK_DSM);
```

config.js

```
import { configure, addDecorator, addParameters } from '@storybook/angular';
import { initDsm } from '@invisionapp/dsm-storybook';

// automatically import all files ending in *.stories.ts
const req = require.context('../src/app', true, /\.stories\.ts$/);
function loadStories() {
  req.keys().forEach(filename => req(filename));
}

//Init Dsm
initDsm({
  addDecorator,
  addParameters,
  callback: () => configure(loadStories, module)
});

configure(loadStories, module);

```

**Comment by CharlJKruger** [comment]
Even pulling down the example app and  running preview in storybook-v5 does the same thing:

'STORYBOOK_DSM' is not recognized as an internal or external command,
operable program or batch file.

Also the port http://localhost:63744/ doesnt work

**Comment by mortal94** [comment]
Hey @CharlJKruger ! you're running it on windows right? we just deployed a new version of `@invisionapp/dsm-storybook` `v0.0.81` that will fix this issue on windows machines. let me know if it fixed the issue for you.
